### ISSUE TITLE
CherrySH seems to not compile, commands created are not found.

### ISSUE THREAD

**Issue by obitvn** [cherry-embedded/CherrySH#1]
![image](https://github.com/user-attachments/assets/8f91a25f-56e9-4ccb-a28a-6b93269b921e)
Hello,

CherrySH is a really elegant shell. I am implementing it on the RP2040 through USB CDC, using the USB library class CherryUSB. Everything seems to be working fine; I can log in normally. However, I can't seem to call the commands that I created based on your example, despite trying many ways as shown in the image.

I have added .vsymtab and .fsymtab to the linker .ld file, but it seems to have no effect or is not in the correct position.
![image](https://github.com/user-attachments/assets/d72144dc-6e07-4aa3-b5b1-dcb717591070)

**Comment by obitvn** [comment]
The issue has been resolved. To use CherrySH, we need to add fsymtab and vsymtab to the linker file to facilitate symbol table calls. For anyone using CherrySH on RP2040, please refer to [this linker file.](https://github.com/RT-Thread-Studio/sdk-bsp-rp2040-raspberry-pico/blob/main/project_0/link.ld)
![image](https://github.com/user-attachments/assets/1dce51e8-b055-45c9-80b2-03f5c531e047)
And add the line
pico_set_linker_script(FlexiCAN_Controller  ${CMAKE_CURRENT_LIST_DIR}/memmap_custom.ld)
in file CMakeList.txt
I think you need to update the note about the symbol table in the README, thank you.

**Comment by sakumisu** [comment]
Thank you, forget to add this in readme.
