### ISSUE TITLE
CherrySH freezes when using the up and down buttons to review history.

### ISSUE THREAD

**Issue by obitvn** [cherry-embedded/CherrySH#2]
Hi,

I'm using CherrySH and encountering the following issue:

 - CherrySH freezes and becomes unresponsive to commands or key presses after I press the up or down arrow keys on the keyboard to review the history. This means that the history feature in the shell is not working.

 - CherrySH does not exit the shell_main() function. I noticed in your example that you're able to run shell_main concurrently with an LED blinking in a while(1) loop, but it doesn't seem to work for me. CherrySH still runs normally, but it gets stuck in the shell_main() function and won't exit.

Am I making any mistakes or missing something? I'm using the csh_config as provided in your example.

**Comment by Egahp** [comment]
Try to pull the new code, it should be that the previous modifications caused the configuration not to take effect. Pull the new code and test it again, the configuration item is CONFIG_CSH_NOBLOCK.

**Comment by obitvn** [comment]
After updating the new code from the repo, it worked without needing to reconfigure. Thank you very much. The freezing issue when pressing the up and down arrow keys to review history still occurs. I will try to find a fix and create a new issue later.
